import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNavigationBar from "@/components/top-navigation-bar";
import Providers from "@/components/providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className} antialiased`}>
      <body>
        <main className="min-h-screen">
          <TopNavigationBar title="Explore Stripe" />
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
